import { Inter } from 'next/font/google'
import './globals.css'
import { NextThemeProvider } from '@/providers/NextThemeProvider'
import NextUIProviderWrapper from '@/providers/NextUiProvider'
import TopNavBar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en"
    className={(inter.className, "dark")}
    style={{
      colorScheme: "dark",
    }}
    >
      <body>
       <NextUIProviderWrapper>
       <NextThemeProvider>
       <div className='flex min-h-screen w-full flex-col items-center'>
        <TopNavBar />
        <main className='flex flex-grow w-full justify-center items-center dark:bg-neutral-950'>
        {children}
        </main>
       </div>
       </NextThemeProvider>
       </NextUIProviderWrapper>
        </body>
    </html>
  )
}
