import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/lib/ThemeProvider'
import NextThemesProvider from '@/lib/NextThemeProvider'
import TopNavbar from '@/components/Navbar'
import Footer from '@/components/Footer/Footer'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en"
    className={(inter.className, "dark")}
    style={{
      colorScheme: "dark",
    }}
    >
      <body className=''>
      <NextThemesProvider>
      <ThemeProvider>
      <TopNavbar />
       {children}
       <Footer />
       </ThemeProvider>
      </NextThemesProvider>
        </body>
    </html>
  )
}
